[project]
name = "oneroof"
version = "0.1.0"
description = "Base-, Variant-, and Consensus-calling under One Proverbial Roof. Work in progress!"
authors = [
    { name = "Nicholas R. Minor", email = "nrminor@wisc.edu" },
    { name = "Andrew J. Lail", email = "ajlail@wisc.edu" },
    { name = "Annabelle Kalweit", email = "akalweit@wisc.edu" },
    { name = "William K. Gardner", email = "wkgardner@wisc.edu" }
]
requires-python = ">= 3.10"
keywords = [
    "science",
    "biology",
    "research",
    "bioinformatics",
    "sequencing",
    "genomics",
    "virus",
    "SARS-CoV-2",
    "H5N1",
    "influenze",
    "haplotyping",
]
classifiers = [
    "Development Status :: 3 - Alpha",

    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",

    "License :: OSI Approved :: MIT License",

    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "polars-lts-cpu>=1.17.1",
    "xlsxwriter>=3.2.0",
    "xlsx2csv>=0.8.4",
    "biopython>=1.84",
    "pysam>=0.22.1",
    "scipy>=1.14.1",
    "paramiko>=3.5.0",
    "plotnine>=0.14.4",
    "loguru>=0.7.0",
]

[build-system]
requires = ["setuptools >= 40.8.0", "cffi >=1.15.0,!=1.17.0"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.setuptools]
py-modules = ["bin"]

[project.scripts]
"oneroof" = "bin.__main__:main"

[tool.pixi.project]
channels = ["conda-forge", "bioconda", "anaconda"]
platforms = ["osx-64", "linux-64"]

[tool.pixi.pypi-dependencies]
oneroof = { path = ".", editable = true }

[tool.pixi.dependencies]
samtools = ">=1.5,<2"
nextflow = ">=24.4.2,<24.5"
minimap2 = ">=2.28,<3"
fastqc = ">=0.12.1,<0.13"
multiqc = ">=1.19,<2"
bcftools = ">=1.16,<2"
chopper = ">=0.8.0,<0.9"
seqkit = ">=2.8.2,<2.9"
snpeff = ">=5.2,<6"
vsearch = ">=2.28.1,<2.29"
nextclade = ">=3.7.1,<3.8"
cutadapt = ">=4.8,<5"
ivar = ">=1.4.2,<1.5"
seqfu = ">=1.20.3,<1.21"
pyyaml = ">=5.4.1,<5.5"
rasusa = ">=2.0.0,<2.1"
python-edlib = ">=1.3.9,<1.4"
mosdepth = ">=0.3.8,<0.4"
pyarrow = ">=16.1.0,<16.2"
rust = ">=1.77.2,<1.80"
csvtk = ">=0.30.0,<0.31"
snpsift = ">=5.2,<6"
loguru = ">=0.7.2,<0.8"
lxml = ">=5.2.2,<5.3"
cffi = ">=1.15.0,<1.17.0"
bbmap = ">=39.1,<40"
bedtools = ">=2.31.1,<3"

[tool.uv]
dev-dependencies = [
    "basedpyright>=1.21.0",
    "ipykernel>=6.29.5",
    "ipython>=8.12.3",
    "jupyter>=0.6.4",
    "just>=0.8.162",
    "mamba>=0.11.3",
    "marimo[sql]>=0.9.10",
    "pip>=24.2",
    "pre-commit>=3.8.0",
    "pytest>=8.3.3",
    "quarto>=0.1.0",
    "ruff>=0.6.4",
    "tox>=4.18.1",
]
compile-bytecode = true

[tool.basedpyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"
