name: Docker CI

on:
    push:
        branches: [ "main", "dev" ]
        paths:
        - '.github/workflows/docker-image.yaml'
        - 'Dockerfile'
        - 'Containerfile'
        - 'pyproject.toml'
        - 'pixi.lock'
    pull_request:
        branches: [ "main" ]
        paths:
        - '.github/workflows/docker-image.yaml'
        - 'Dockerfile'
        - 'Containerfile'
        - 'pyproject.toml'
        - 'pixi.lock'

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: docker build --file Containerfile --tag oneroof:ci_test_$(date +%s) .
